workflows:
  simple-workflow:
    name: Build the android app
    instance_type: mac_mini
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: master
      cancel_previous_builds: true
    scripts:
      - name: Run tests
        script: ./gradlew test
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - azur.haljeta@ministryofprogramming.com