workflows:
  simple-workflow:
    name: Build the android app
    environment:
      groups:
        - MyGroup
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore_placeholder
    instance_type: mac_mini
    triggering:
      events:
        - pull_request
        - push
      cancel_previous_builds: false
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
    scripts:
      - name: Decode keystore
        script: echo $ENCODED_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Update version code
        script: sed -i '' "s/versionCode.*/versionCode `date +%s`/g" app/build.gradle
      #- name: Run tests
      #  script: ./gradlew test
      - name: Build release apk
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $ANDROID_FIREBASE_APP_ID
          groups:
            - MyQAs