definitions:
  - &run-unit-tests
    name: Run unit tests
    script: ./gradlew test
  - &prepare-vars
    CM_KEYSTORE_PATH: /tmp/keystore_placeholder
  - &caches
    - $HOME/.gradle/caches

workflows:
  check-pr:
    name: Validate PR
    environment:
      groups:
        - MyGroup
      vars:
        *prepare-vars
    instance_type: mac_mini
    cache:
      cache_paths:
        *caches
    triggering:
      events:
        - pull_request
      cancel_previous_builds: false
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
    scripts:
      - *run-unit-tests
  simple-workflow:
    name: Deploy app
    environment:
      groups:
        - MyGroup
      vars:
        *prepare-vars
    instance_type: mac_mini
    #cache:
    #  cache_paths:
    #    *caches
    triggering:
      events:
        - push
      cancel_previous_builds: false
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
    scripts:
      - name: Decode keystore
        script: echo $ENCODED_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Keystore checksum
        script: md5 $CM_KEYSTORE_PATH
      - name: Update version code
        script: sed -i '' "s/versionCode.*/versionCode `date +%s`/g" app/build.gradle
      - *run-unit-tests
      - name: Build release apk
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_JSON
        android:
          artifact_type: apk
          app_id: $ANDROID_FIREBASE_APP_ID
          groups:
            - MyQAs