definitions:
  - &run-unit-tests
    name: Run unit tests
    script: ./gradlew test
  - &prepare-vars
    CM_KEYSTORE_PATH: /tmp/keystore_placeholder
  - &caches
    - $HOME/.gradle/caches

workflows:
  check-pr:
    name: Validate PR
    environment:
      groups:
        - MyGroup
      vars:
        *prepare-vars
    instance_type: mac_mini
    cache:
      cache_paths:
        *caches
    triggering:
      events:
        - pull_request
      cancel_previous_builds: false
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
    scripts:
      - *run-unit-tests
  deploy-workflow:
    name: Deploy app
    environment:
      groups:
        - MyGroup
      vars:
        *prepare-vars
    instance_type: mac_mini
    cache:
      cache_paths:
        *caches
    triggering:
      events:
        - push
      cancel_previous_builds: true
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
    when:
      condition: event.name.name == 'azurmop'
    scripts:
      - name: Clean
        script: ./gradlew clean
      - name: Decode keystore
        script: echo $ENCODED_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Update version code
        script: sed -i '' "s/versionCode=.*/versionCode=`date +%s`/g" version.properties
      - *run-unit-tests
      - name: Copy test results
        script: cp -r app/build/reports/tests/testReleaseUnitTest/ $CM_EXPORT_DIR/tests/
      - name: Build release apk
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      slack:
        channel: '#general'
        notify_on_build_start: true
        notify:
          failure: true
          success: true
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_JSON
        android:
          artifact_type: apk
          app_id: $ANDROID_FIREBASE_APP_ID
          groups:
            - MyQAs