workflows:
  simple-workflow:
    name: Build the android app
    environment:
      groups:
        - MyGroup
    instance_type: mac_mini
    triggering:
      events:
        - pull_request
      cancel_previous_builds: false
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
    scripts:
      - name: Run tests
        script: ./gradlew test
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $ANDROID_FIREBASE_APP_ID
          groups:
            - MyQAs