definitions:
  - &run-unit-tests
    name: Run unit tests
    script: ./gradlew test
  - &prepare-vars
    CM_KEYSTORE_PATH: /tmp/keystore_placeholder
  - &caches
    - $HOME/.gradle/caches

workflows:
  check-pr:
    name: Validate PR
    environment:
      groups:
        - MyGroup
      vars:
        *prepare-vars
    instance_type: mac_mini
    cache:
      cache_paths:
        *caches
    triggering:
      events:
        - pull_request
      cancel_previous_builds: false
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
    scripts:
      - *run-unit-tests
  deploy-workflow:
    name: Deploy app
    environment:
      groups:
        - MyGroup
      vars:
        *prepare-vars
    instance_type: mac_mini
    cache:
      cache_paths:
        *caches
    triggering:
      events:
        - push
      cancel_previous_builds: true
      branch_patterns:
        - pattern: 'master'
          include: true
          source: false
    #when:
    #  condition: event.pusher.name == "azurmop"
    scripts:
      - name: Echo Build number
        script: |
          echo $BUILD_NUMBER
          echo $PROJECT_BUILD_NUMBER
      - name: Clean
        script: ./gradlew clean
      - name: Send a irrelevant Slack message
        script: |
                curl -X GET -H 'Authorization: Bearer '"$SLACK_BOT_TOKEN"'' 'https://slack.com/api/chat.postMessage?channel=general&text=codemagic'
      - name: Decode keystore
        script: echo $ENCODED_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Update version code
        script: sed -i '' "s/versionCode=.*/versionCode=`date +%s`/g" version.properties
      #- name: Set branch name
      #  script: sed -i '' "s|branch=.*|branch=$CM_BRANCH|g" version.properties
      - *run-unit-tests
      - name: Copy test results
        script: cp -r app/build/reports/tests/testReleaseUnitTest/ $CM_EXPORT_DIR/tests/
      - name: Build release apk
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      slack:
        channel: '#general'
        notify_on_build_start: true
        notify:
          failure: true
          success: true
      email:
        recipients:
          - azur.haljeta@gmail.com
          - azur.haljeta@ministryofprogramming.com
        notify:
          success: true
          failure: true
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          artifact_type: apk
          app_id: $ANDROID_FIREBASE_APP_ID
          groups:
            - MyQAs